name: Build extension

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Pack extension to ZIP
        run: |
          zip -r minimal-new-tab-${{github.ref_name}}.zip dist
      - uses: actions/upload-artifact@v2
        with:
          name: minimal-new-tab-${{github.ref_name}}.zip
          path: minimal-new-tab-${{github.ref_name}}.zip
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: minimal-new-tab-${{github.ref_name}}.zip
          tag: "${{github.ref_name}}"
