name: Build extension

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: minimal-new-tab
          path: dist
